#!/usr/bin/env php
<?php

/**
 * Try and find a composer autoload file, hope for the best if not
 */
if (is_file(__DIR__.'/vendor/autoload.php')) {
    require_once __DIR__.'/vendor/autoload.php';
} else if (is_file(__DIR__.'/../../autoload.php')) {
    require_once __DIR__.'/../../autoload.php'; 
}

$app = require __DIR__.'/src/app.php';
$console = require __DIR__.'/src/console.php';
$console->run();
